<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.2.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="NativeTray" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="*.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Backdrop.WPF\Backdrop.WPF.csproj" />
  </ItemGroup>
</Project>